[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "learning_center_agent"
version = "0.1.0"
description = "Learning Center Agent"
readme = "README.md"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["learning_center_agent"]
