apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dakota-redis
  namespace: dakota
spec:
  serviceName: dakota-redis
  replicas: 1
  selector:
    matchLabels:
      app: dakota-redis
  template:
    metadata:
      labels:
        app: dakota-redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
          - redis-server
          - --appendonly
          - "yes"
          - --maxmemory
          - "2gb"
          - --maxmemory-policy
          - "allkeys-lru"
          - --save
          - "900 1"
          - --save
          - "300 10"
          - --save
          - "60 10000"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"
        volumeMounts:
        - name: redis-data
          mountPath: /data
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: redis-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: dakota-redis
  namespace: dakota
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    app: dakota-redis